//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExperts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PackageId { get; set; }
        public string PkgName { get; set; }
        public Nullable<System.DateTime> PkgStartDate { get; set; }
        public Nullable<System.DateTime> PkgEndDate { get; set; }
        public string PkgDesc { get; set; }
        public decimal PkgBasePrice { get; set; }
        public Nullable<decimal> PkgAgencyCommission { get; set; }
    }
}
